name: End-to-end tests
on: [workflow_dispatch]
jobs:
  cypress-testing:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start containers
        run: docker-compose --env-file .env up -d --build

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          wait-on: 'http://[::1]:4000'
          browser: chrome


  build-and-push:
    needs: cypress-testing
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build-image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: nico1512/app:v1.0.1
          