name: End-to-end tests
on: [push, ]
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Start containers
        run: docker-compose -f "docker/docker-compose.yml" up -d --build      
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      # - name: Cypress run
      #   uses: cypress-io/github-action@v6
      #   with: 
      #     wait-on: 'http://[::1]:4000'

      - name: Execute the Tests
        run: npm run test
          