name: Matrix test

on: [push]

jobs:  
  cypress-testing:
    strategy:
      matrix:
        include: 
          - dockerfile: Dockerfile
            image: nico1512/app:v1.0.2
          - dockerfile: Dockerfile
            image: nico1512/app:v1.0.3
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: nico1512/app:v1.0.0
          outputs: type=docker,dest=/tmp/nico1512.app.tar

      - name: Start containers
        run: |
            docker load --input /tmp/nico1512.app.tar
            docker-compose --env-file .env up -d

      - name: Cypress run
        id: cypress-run
        uses: cypress-io/github-action@v6
        with:
          wait-on: 'http://[::1]:4000'
          browser: chrome


  build-and-push:
    needs: cypress-testing
    strategy:
      matrix:
        include: 
          - dockerfile: Dockerfile
            image: nico1512/app:v1.0.2
          - dockerfile: Dockerfile
            image: nico1512/app:v1.0.3
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: nico1512_dockerimage

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ matrix.image }}
          